# Generated by Django 3.2.4 on 2021-06-23 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_kakao_id'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_posting', to='postings.posting'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='users.user'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='back_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_back_color', to='postings.color'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='item_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_item_color', to='postings.color'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='like',
            field=models.ManyToManyField(related_name='posting_like', through='postings.Like', to='users.User'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='users.user'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
