# Generated by Django 3.2.4 on 2021-06-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=40, null=True)),
                ('profile_image', models.CharField(max_length=200, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
